highlighter: rouge
permalink: pretty
markdown: kramdown

title: Legacy Kode
name: Agung Setiawan' Personal Site
url: https://legacykode.com
feed: /atom.xml

author: Agung Setiawan
contact:
    email: com.agungsetiawan@gmail.com

css:
    - /css/base.css
    - /lib/font-awesome/css/font-awesome.min.css
    - //fonts.googleapis.com/css?family=Droid+Sans:400,700

gems:
    - jekyll-redirect-from
    - jekyll-mentions

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
    - TODO.md
    - vendor
